import type { ResearchNode } from './types';

/**
 * Static tech tree (v1). Sacred hard gates from docs/RESEARCH.md.
 * Starter blueprints are not nodes — they begin unlocked.
 * Caps: ≤3 roots (empty requires), ≤3 children per node (limits, not targets).
 */
export const RESEARCH_NODES: ResearchNode[] = [
  {
    id: 'bp-pipe',
    name: 'Plumbing',
    description: 'Lay pipes and spray water onto climbers — gateway to fluids and steam.',
    kind: 'blueprint',
    unlocksBlueprints: ['pipe', 'hydrantRoom'],
    requires: [],
    startCost: { souls: 8 },
    progressRequired: 25,
  },
  {
    id: 'bp-slot',
    name: 'Arrow Slots',
    description: 'Soldier firing positions (requires Guardroom housing).',
    kind: 'blueprint',
    unlocksBlueprints: ['slotRoom'],
    requires: [],
    startCost: { souls: 6 },
    progressRequired: 20,
  },
  {
    id: 'bp-boiler',
    name: 'Boilers',
    description: 'Convert water heat into steam pressure.',
    kind: 'blueprint',
    unlocksBlueprints: ['boilerRoom'],
    requires: ['bp-pipe'],
    startCost: { souls: 10, metal: 8 },
    progressRequired: 35,
  },
  {
    id: 'bp-mana-spring',
    name: 'Mana Springs',
    description: 'Water-fed springs where magi regenerate mana.',
    kind: 'blueprint',
    unlocksBlueprints: ['manaSpringRoom'],
    requires: ['bp-pipe'],
    startCost: { souls: 12 },
    progressRequired: 35,
  },
  {
    id: 'bp-pump',
    name: 'Water Pumps',
    description: 'Extend how high pipe water can climb.',
    kind: 'blueprint',
    unlocksBlueprints: ['pumpRoom'],
    requires: ['bp-pipe'],
    startCost: { souls: 8, metal: 6 },
    progressRequired: 30,
  },
  {
    id: 'bp-steam-turret',
    name: 'Steam Turrets',
    description: 'Pressurized steam weapons — needs pipes and boilers.',
    kind: 'blueprint',
    unlocksBlueprints: ['steamTurretRoom'],
    // Pipe is implied via bp-boiler (keeps pipe out-degree ≤3).
    requires: ['bp-boiler'],
    startCost: { souls: 15, metal: 10 },
    progressRequired: 45,
  },
  {
    id: 'exp-boiler',
    name: 'Boiler Expansion',
    description: 'Improve boiler steam throughput.',
    kind: 'expansion',
    unlocksModifications: ['boilerExpansion'],
    requires: ['bp-boiler'],
    startCost: { souls: 12, metal: 10 },
    progressRequired: 40,
  },
  {
    id: 'bp-forge',
    name: 'Forgecraft',
    description: 'Forge rooms that feed fire into pipe networks.',
    kind: 'blueprint',
    unlocksBlueprints: ['forgeRoom'],
    requires: ['bp-boiler'],
    startCost: { souls: 8, metal: 4 },
    progressRequired: 25,
  },
  {
    id: 'bp-flame-turret',
    name: 'Flame Turrets',
    description: 'Fire-pipe weapons — needs forgecraft.',
    kind: 'blueprint',
    unlocksBlueprints: ['flameTurretRoom'],
    requires: ['bp-forge'],
    startCost: { souls: 15, metal: 8 },
    progressRequired: 40,
  },
  {
    id: 'bp-leyline-research',
    name: 'Leyline Research',
    description: 'Build Leyline Research rooms on energy bands to awaken successive school spells.',
    kind: 'blueprint',
    unlocksBlueprints: ['leylineResearchRoom'],
    requires: ['bp-mana-spring'],
    startCost: { souls: 10, stone: 8 },
    progressRequired: 30,
  },
  {
    id: 'bp-elevator',
    name: 'Elevators',
    description: 'Fast vertical shafts for staff.',
    kind: 'blueprint',
    unlocksBlueprints: ['elevator'],
    requires: ['bp-leyline-research'],
    startCost: { souls: 10, metal: 5 },
    progressRequired: 30,
  },
  {
    id: 'tech-overhang',
    name: 'Cantilever Framing',
    description: 'Spire blocks may overhang supported framing by one cell.',
    kind: 'technology',
    requires: ['bp-elevator'],
    startCost: { souls: 5, metal: 4 },
    progressRequired: 20,
  },
  {
    id: 'exp-guardroom',
    name: 'Guardroom Expansion',
    description: 'Double soldier housing capacity.',
    kind: 'expansion',
    unlocksModifications: ['guardroomExpansion'],
    requires: ['bp-pump'],
    startCost: { souls: 8, gold: 10 },
    progressRequired: 25,
  },
  {
    id: 'exp-chamber',
    name: 'Chamber Expansion',
    description: 'House a second mage.',
    kind: 'expansion',
    unlocksModifications: ['chamberExpansion'],
    requires: ['exp-guardroom'],
    startCost: { souls: 10, gold: 10 },
    progressRequired: 25,
  },
  {
    id: 'exp-quarters',
    name: 'Quarters Expansion',
    description: 'Double laborer housing capacity.',
    kind: 'expansion',
    unlocksModifications: ['quartersExpansion'],
    requires: ['exp-chamber'],
    startCost: { souls: 8, gold: 8 },
    progressRequired: 25,
  },
  {
    id: 'exp-slot',
    name: 'Slot Expansion',
    description: 'Raise slot headcount capacity.',
    kind: 'expansion',
    unlocksModifications: ['slotExpansion'],
    requires: ['bp-slot'],
    startCost: { souls: 10, metal: 5 },
    progressRequired: 30,
  },
  {
    id: 'bp-moat',
    name: 'Moats',
    description: 'Ground-edge routing aura.',
    kind: 'blueprint',
    unlocksBlueprints: ['moat'],
    requires: ['bp-slot'],
    startCost: { souls: 5, stone: 5 },
    progressRequired: 20,
  },
  {
    id: 'bp-glacis',
    name: 'Glacis',
    description: 'Ground-edge soft funnel.',
    kind: 'blueprint',
    unlocksBlueprints: ['glacis'],
    requires: ['bp-moat'],
    startCost: { souls: 5, stone: 5 },
    progressRequired: 20,
  },
  {
    id: 'bp-stakes',
    name: 'Stakes',
    description: 'Cost + slow funnel stakes.',
    kind: 'blueprint',
    unlocksBlueprints: ['stakes'],
    requires: ['bp-glacis'],
    startCost: { souls: 7, stone: 4 },
    progressRequired: 25,
  },
  {
    id: 'bp-parapet',
    name: 'Parapets',
    description: 'Top-face shell routing.',
    kind: 'blueprint',
    unlocksBlueprints: ['parapet'],
    requires: ['bp-slot'],
    startCost: { souls: 6 },
    progressRequired: 22,
  },
  {
    id: 'bp-cornice',
    name: 'Cornices',
    description: 'Underhang shell denial.',
    kind: 'blueprint',
    unlocksBlueprints: ['cornice'],
    requires: ['bp-parapet'],
    startCost: { souls: 6 },
    progressRequired: 22,
  },
  {
    id: 'bp-barbican',
    name: 'Barbicans',
    description: 'Gate-face band costs.',
    kind: 'blueprint',
    unlocksBlueprints: ['barbican'],
    requires: ['bp-parapet'],
    startCost: { souls: 12, stone: 8 },
    progressRequired: 35,
  },
];

export function getResearchNode(id: string): ResearchNode | undefined {
  return RESEARCH_NODES.find((n) => n.id === id);
}

export function listResearchNodes(): ResearchNode[] {
  return RESEARCH_NODES;
}
